feature(reset): refactor the reset service to reset the cluster state completely
kubernetes-sigs/kube-scheduler-simulator pull request #229
Opened 2022-09-18 15:06 UTC by sanposhiho

… completely

#### What type of PR is this?

/area simulator
/kind feature
/kind cleanup

#### What this PR does / why we need it:

Currently, reset service tries to remove all **supported** resources. 
But, those who use other resources want to reset the cluster completely; including all unsupported resources.
(+ Especially, before running Scenario, we wanna clean up all resources.)

---

And, besides those enhancements, we also can remove `DeleteCollection` method from all resource services.
It partly contributes to https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/139.

#### Which issue(s) this PR fixes:

Fixes #218

#### Special notes for your reviewer:

/label tide/merge-method-squash

2022-10-31 10:59 UTC, sanposhiho commented
@196Ikuchil rebased. 🙏

2022-10-31 17:09 UTC, 196Ikuchil requested changes
Thank you for the PR.
I left some comments.

And this has a familiar problem.
It's a resource deletion of PriorityClass prefixed with "system-".

This is, after the resetting, `system-cluster-critical` and `system-node-critical` would also be deleted.
To avoid this, we should check the internal data of the etcd when deletion, or backup the data with these data, or restart with api-server, I think.
(This issue plagues us all time.. 🤔 )

2022-11-15 14:58 UTC, sanposhiho commented on simulator/reset/reset.go
> +		return nil, xerrors.Errorf("delete all data in etcd: %w", err)
Fixed. 🙏

2022-12-11 14:55 UTC, 196Ikuchil reviewed
Thank you!
This PR works fine on my local:+1:

/lgtm

2022-12-11 15:03 UTC, merged